### ISSUE TITLE
Dark theme behaves differently from light theme?

### ISSUE THREAD

**Issue by spencerc99** [lkytal/vscode-theme-flatui#10]
I'm noticing for Python that the light theme will highlight any function it sees with purple as so:
![image](https://user-images.githubusercontent.com/14796580/44942487-cdc8c300-ad77-11e8-8be9-82585ee93454.png)

but for the dark theme it won't detect all of them?
![image](https://user-images.githubusercontent.com/14796580/44942488-dd480c00-ad77-11e8-97f3-83e0a9363480.png)
As you can see, it only finds `print` but doesn't highlight `strip`, `format()` or `word_to_category`

**Comment by lkytal** [comment]
Shall improved in version 1.4.8.
