### ISSUE TITLE
Not working on Ubuntu

### ISSUE THREAD

**Issue by tamj0rd2** [lkytal/vscode-theme-flatui#3]
This works perfectly on Windows but not on Ubuntu.

**Expected behaviour**
Choosing the "FlatUI Dark" theme changes the theme.

**Actual behaviour**
Nothing happens. The theme stays on whichever one was previously chosen.

**Error from debug console**
```Unable to load /home/tam/.vscode/extensions/lkytal.flatui-1.4.0/themes/flatDark.tmtheme: Problems loading tmTheme file /home/tam/.vscode/extensions/lkytal.flatui-1.4.0/themes/flatDark.tmtheme: ENOENT: no such file or directory, open '/home/tam/.vscode/extensions/lkytal.flatui-1.4.0/themes/flatDark.tmtheme'```

**Fix**
Changing `./themes/flatDark.tmtheme` to `./themes/flatDark.tmTheme` in package.json fixes the issue, since paths are case sensitive.

**Comment by tamj0rd2** [comment]
Beautiful theme btw :)

**Comment by lkytal** [comment]
Thanks for point out.
