### ISSUE TITLE
Text selection invisible in Git Diff

### ISSUE THREAD

**Issue by torzuoliH** [lkytal/vscode-theme-flatui#6]
Using **Light style**, when doing a *git diff* in source code control tab, selected text is not visible.  Whether it be in addition or deletion panel, we can't see what is selected.

![capture](https://user-images.githubusercontent.com/7328625/30203536-8f4a95b8-9482-11e7-9fdb-718db8ed9c02.PNG)

It's a little bit better with **Dark Style**.

**Comment by lkytal** [comment]
Shall have improved in 1.4.2

**Comment by torzuoliH** [comment]
Indeed seems a little bit contrasted with d1da05
