### ISSUE TITLE
Flatui Immersed Theme Issues?

### ISSUE THREAD

**Issue by leeyongda** [lkytal/vscode-theme-flatui#9]
Select Immersed Theme .
filename git uncommit that filename foreground color is yellow ? 
The yellow  colors there are just so vivid . How to change the colors . Normal is Green Color .

Example pic:

![wx20180423-132513](https://user-images.githubusercontent.com/11832476/39108478-0c453782-46fb-11e8-9cd0-e38a168c2e50.png)
![wx20180423-133446](https://user-images.githubusercontent.com/11832476/39108504-2763d65e-46fb-11e8-918e-694f4c2680b7.png)

**Comment by lkytal** [comment]
Well in my local VSCode those files are not in light yellow, are you using any other themes as well?

**Comment by leeyongda** [comment]
When I use git .
When git uncommit file that filename foreground color is yellow .

**Comment by lkytal** [comment]
However, I see dark yellow here for my uncommitted charges, any idea?
<img width="172" alt="sp" src="https://user-images.githubusercontent.com/3395795/39648511-6e2db8f8-4fb0-11e8-8e4d-af11d1c61521.png">
